import { JournalEntryResponse } from '@/types/ledger.types';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { formatDate, formatCurrency } from '@/lib/utils';
import { Calendar, Receipt, ChevronRight, Wand2 } from 'lucide-react';

interface JournalEntryCardProps {
  entry: JournalEntryResponse;
  onView: () => void;
}

export function JournalEntryCard({ entry, onView }: JournalEntryCardProps) {
  return (
    <Card className="hover:shadow-md transition-shadow group flex flex-col md:flex-row md:items-center py-4 px-6 gap-4">
      <div className="flex-1 space-y-1">
        <div className="flex items-center gap-2 mb-1">
          <div className="text-sm font-semibold text-navy-900 flex items-center gap-1.5">
            <Receipt className="h-4 w-4 text-slate-400" />
            Entry for Invoice {entry.invoice.invoiceNumber}
          </div>
          {entry.isAutoGenerated && (
            <Badge variant="ghost" className="gap-1 px-1.5 py-0 text-[10px]">
              <Wand2 className="h-3 w-3" />
              Auto
            </Badge>
          )}
        </div>
        <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">
          <div className="flex items-center gap-1.5">
            <Calendar className="h-3.5 w-3.5" />
            {formatDate(entry.entryDate)}
          </div>
          <div className="flex items-center gap-1.5 font-medium text-slate-700">
            Total {formatCurrency(entry.totalDebit)}
          </div>
        </div>
      </div>

      <div className="flex items-center gap-4 border-t md:border-t-0 md:border-l pt-4 md:pt-0 md:pl-6 border-slate-100">
        <div className="text-right hidden sm:block">
          <div className="text-xs text-muted-foreground">Lines</div>
          <div className="text-sm font-semibold text-slate-900">{entry.lines.length}</div>
        </div>
        <Button 
          variant="outline" 
          size="sm" 
          onClick={onView} 
          className="ml-auto md:ml-0 group-hover:border-brand-500 group-hover:bg-brand-50 group-hover:text-brand-700 transition-all"
        >
          View Details
          <ChevronRight className="ml-1.5 h-3.5 w-3.5" />
        </Button>
      </div>
    </Card>
  );
}
