import { JournalEntryResponse } from '@/types/ledger.types';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription, 
  DialogFooter 
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { formatDate, formatCurrency } from '@/lib/utils';
import { Calendar, CheckCircle2, AlertCircle } from 'lucide-react';

interface JournalEntryDetailModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  entry: JournalEntryResponse | null;
  onDelete?: (id: string) => void;
  isDeleting?: boolean;
}

export function JournalEntryDetailModal({ 
  open, 
  onOpenChange, 
  entry, 
  onDelete, 
  isDeleting 
}: JournalEntryDetailModalProps) {
  if (!entry) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <div className="flex items-center justify-between pr-8">
            <DialogTitle>Journal Entry Details</DialogTitle>
            {entry.isAutoGenerated && (
              <Badge variant="ghost">Auto-Generated</Badge>
            )}
          </div>
          <DialogDescription>
            Reference: Invoice {entry.invoice.invoiceNumber}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Metadata Grid */}
          <div className="grid grid-cols-2 gap-4 bg-slate-50 p-4 rounded-xl border">
            <div>
              <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Entry Date</div>
              <div className="flex items-center gap-2 mt-1 font-medium text-slate-700">
                <Calendar className="h-4 w-4 text-slate-400" />
                {formatDate(entry.entryDate)}
              </div>
            </div>
            <div>
              <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Status</div>
              <div className="flex items-center gap-1.5 mt-1 font-medium">
                {entry.isBalanced ? (
                  <span className="text-green-600 flex items-center gap-1">
                    <CheckCircle2 className="h-4 w-4" /> Balanced
                  </span>
                ) : (
                  <span className="text-red-600 flex items-center gap-1">
                    <AlertCircle className="h-4 w-4" /> Unbalanced
                  </span>
                )}
              </div>
            </div>
            {entry.description && (
              <div className="col-span-2 border-t pt-3 mt-1">
                <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Description</div>
                <div className="text-sm text-slate-600 mt-1">{entry.description}</div>
              </div>
            )}
          </div>

          {/* Ledger Lines */}
          <div className="rounded-xl border overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 border-b font-medium text-slate-500">
                <tr>
                  <th className="py-2.5 px-4">Account</th>
                  <th className="py-2.5 px-4 text-right">Debit</th>
                  <th className="py-2.5 px-4 text-right">Credit</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {entry.lines.map((line) => (
                  <tr key={line.id}>
                    <td className="py-3 px-4 font-medium text-slate-900">{line.ledger.name}</td>
                    <td className="py-3 px-4 text-right text-slate-600">
                      {line.debit ? formatCurrency(line.debit) : '-'}
                    </td>
                    <td className="py-3 px-4 text-right text-slate-600">
                      {line.credit ? formatCurrency(line.credit) : '-'}
                    </td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="bg-slate-50/50 font-bold border-t">
                <tr>
                  <td className="py-3 px-4 text-slate-900">Total</td>
                  <td className="py-3 px-4 text-right text-slate-900">{formatCurrency(entry.totalDebit)}</td>
                  <td className="py-3 px-4 text-right text-slate-900">{formatCurrency(entry.totalCredit)}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>

        <DialogFooter className="flex-row sm:justify-between items-center sm:space-x-2">
          <div className="text-xs text-muted-foreground">
            Created on {formatDate(entry.createdAt)}
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Close
            </Button>
            {onDelete && !entry.isAutoGenerated && (
              <Button 
                variant="destructive" 
                onClick={() => onDelete(entry.id)}
                loading={isDeleting}
              >
                Delete Entry
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
