import { useJournalEntries } from '@/hooks/useInvoices';
import { formatCurrency, formatDate } from '@/lib/utils';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { CheckCircle2, AlertCircle } from 'lucide-react';
import { EmptyState } from '@/components/ui/empty-state';
import { FileDigit } from 'lucide-react';

interface JournalEntriesTabProps {
  invoiceId: string;
}

export function JournalEntriesTab({ invoiceId }: JournalEntriesTabProps) {
  const { data: entries, isLoading } = useJournalEntries(invoiceId);

  if (isLoading) {
    return (
      <Card>
        <CardContent className="p-6 space-y-4">
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-10 w-full" />
        </CardContent>
      </Card>
    );
  }

  if (!entries || entries.length === 0) {
    return (
      <EmptyState
        icon={FileDigit}
        title="No Journal Entries"
        description="Accounting entries are automatically generated when an invoice is fully approved."
      />
    );
  }

  return (
    <div className="space-y-6">
      {entries.map((entry) => (
        <Card key={entry.id} className="overflow-hidden border-slate-200">
          <CardHeader className="bg-slate-50 border-b pb-4 pt-4 px-6 flex flex-row items-center justify-between">
            <div>
              <CardTitle className="text-base flex items-center gap-2">
                Journal Entry
                {entry.isAutoGenerated && (
                  <span className="text-xs font-normal text-brand-600 bg-brand-50 px-2 py-0.5 rounded border border-brand-100 uppercase tracking-wide">
                    Auto-Generated
                  </span>
                )}
              </CardTitle>
              <div className="text-sm text-slate-500 mt-1">
                {formatDate(entry.entryDate)} {entry.description && `• ${entry.description}`}
              </div>
            </div>
            {entry.isBalanced ? (
              <div className="flex items-center gap-1.5 text-green-600 bg-green-50 px-2.5 py-1 rounded-full text-sm font-medium border border-green-200">
                <CheckCircle2 className="h-4 w-4" /> Balanced
              </div>
            ) : (
              <div className="flex items-center gap-1.5 text-red-600 bg-red-50 px-2.5 py-1 rounded-full text-sm font-medium border border-red-200">
                <AlertCircle className="h-4 w-4" /> Unbalanced
              </div>
            )}
          </CardHeader>

          <CardContent className="p-0">
            <table className="w-full text-sm text-left">
              <thead className="bg-white text-slate-500 font-medium border-b">
                <tr>
                  <th className="px-6 py-3">Account</th>
                  <th className="px-6 py-3 text-right">Debit</th>
                  <th className="px-6 py-3 text-right">Credit</th>
                </tr>
              </thead>
              <tbody className="divide-y text-slate-700">
                {entry.lines.map((line) => (
                  <tr key={line.id} className="hover:bg-slate-50/50">
                    <td className="px-6 py-4 font-medium text-navy-900">
                      {line.ledger.name}
                    </td>
                    <td className="px-6 py-4 text-right tabular-nums">
                      {line.debit ? formatCurrency(line.debit) : '—'}
                    </td>
                    <td className="px-6 py-4 text-right tabular-nums">
                      {line.credit ? formatCurrency(line.credit) : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="bg-slate-50 border-t font-semibold text-navy-900">
                <tr>
                  <td className="px-6 py-4 text-right">Total</td>
                  <td className="px-6 py-4 text-right tabular-nums">
                    {formatCurrency(entry.totalDebit)}
                  </td>
                  <td className="px-6 py-4 text-right tabular-nums">
                    {formatCurrency(entry.totalCredit)}
                  </td>
                </tr>
              </tfoot>
            </table>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
