export type InvoiceStatus =
  | 'DRAFT'
  | 'SUBMITTED'
  | 'APPROVED'
  | 'REJECTED'
  | 'FAILED';

export type SyncStatus = 'NOT_SYNCED' | 'SYNCED' | 'ERROR';

export interface InvoiceItemResponse {
  id:          string;
  description: string;
  hsnCode:     string | null;
  quantity:    string;
  unitPrice:   string;
  amount:      string;
  taxRate:     string;
}

export interface InvoiceResponse {
  id:              string;
  invoiceNumber:   string;
  invoiceDate:     string;
  totalAmount:     string;
  gstAmount:       string;
  cgstAmount:      string | null;
  sgstAmount:      string | null;
  igstAmount:      string | null;
  status:          InvoiceStatus;
  syncStatus:      SyncStatus;
  confidenceScore: number | null;
  organizationId:  string;
  clientId:        string | null;
  documentId:      string | null;
  client: {
    id:    string;
    name:  string;
    gstin: string | null;
  } | null;
  items:            InvoiceItemResponse[];
  submittedAt:      string | null;
  approvedAt:       string | null;
  rejectedAt:       string | null;
  rejectionReason:  string | null;
  reopenedAt:       string | null;
  reopenReason:     string | null;
  createdAt:        string;
  updatedAt:        string;
}

export interface InvoiceListItem {
  id:            string;
  invoiceNumber: string;
  invoiceDate:   string;
  totalAmount:   string;
  gstAmount:     string;
  status:        InvoiceStatus;
  syncStatus:    SyncStatus;
  clientId:      string | null;
  client: {
    id:   string;
    name: string;
  } | null;
  createdAt: string;
}

export interface InvoiceHistoryEntry {
  action:     string;
  fromStatus: string | null;
  toStatus:   string;
  performedBy: {
    id:       string;
    fullName: string;
    email:    string;
  } | null;
  details:   Record<string, unknown>;
  ipAddress: string | null;
  createdAt: string;
}

export interface JournalLineResponse {
  id:       string;
  ledgerId: string;
  ledger: { id: string; name: string };
  debit:    string | null;
  credit:   string | null;
}

export interface JournalEntryResponse {
  id:              string;
  invoiceId:       string;
  entryDate:       string;
  description:     string | null;
  isAutoGenerated: boolean;
  lines:           JournalLineResponse[];
  totalDebit:      string;
  totalCredit:     string;
  isBalanced:      boolean;
  createdAt:       string;
}

export interface CreateInvoiceItemInput {
  description: string;
  hsnCode?:    string;
  quantity:    number;
  unitPrice:   number;
  amount:      number;
  taxRate:     number;
}

export interface CreateInvoiceInput {
  invoiceNumber:  string;
  invoiceDate:    string;
  clientId?:      string;
  documentId?:    string;
  cgstAmount?:    number;
  sgstAmount?:    number;
  igstAmount?:    number;
  gstAmount:      number;
  totalAmount:    number;
  items:          CreateInvoiceItemInput[];
}

export interface InvoiceListFilters {
  status?:    InvoiceStatus;
  clientId?:  string;
  syncStatus?: SyncStatus;
  dateFrom?:  string;
  dateTo?:    string;
  search?:    string;
  page?:      number;
  limit?:     number;
}

export interface ClientItem {
  id:    string;
  name:  string;
  gstin: string | null;
}

export interface WorkflowActionResponse {
  invoiceId:      string;
  previousStatus: InvoiceStatus;
  currentStatus:  InvoiceStatus;
  actionAt:       string;
  actionBy: {
    id:       string;
    fullName: string;
    email:    string;
  };
  message: string;
}
