export interface LedgerListItem {
  id:             string;
  name:           string;
  organizationId: string;
  createdAt:      string;
  _count: {
    journalLines: number;
  };
}

export interface LedgerDetailItem extends LedgerListItem {
  journalLines: JournalLineDetail[];
  totalDebit:   string;
  totalCredit:  string;
}

export interface JournalLineDetail {
  id:       string;
  ledgerId: string;
  debit:    string | null;
  credit:   string | null;
  journal: {
    id:        string;
    invoiceId: string;
    entryDate: string;
  };
}

export interface LedgerBalanceSummary {
  ledgerId:    string;
  ledgerName:  string;
  totalDebit:  string;
  totalCredit: string;
  netBalance:  string;
}

export interface CreateLedgerInput {
  name: string;
}

export interface JournalEntryResponse {
  id:              string;
  invoiceId:       string;
  invoice: {
    id:            string;
    invoiceNumber: string;
    totalAmount:   string;
    status:        string;
  };
  entryDate:       string;
  description:     string | null;
  isAutoGenerated: boolean;
  lines:           JournalLineResponse[];
  totalDebit:      string;
  totalCredit:     string;
  isBalanced:      boolean;
  createdAt:       string;
}

export interface JournalLineResponse {
  id:       string;
  ledgerId: string;
  ledger: {
    id:   string;
    name: string;
  };
  debit:    string | null;
  credit:   string | null;
}

export interface CreateJournalEntryInput {
  invoiceId:    string;
  entryDate:    string;
  description?: string;
  lines: {
    ledgerId: string;
    debit?:   number;
    credit?:  number;
  }[];
}

export interface JournalEntryFilters {
  invoiceId?: string;
  dateFrom?:  string;
  dateTo?:    string;
  page?:      number;
  limit?:     number;
}

export interface LedgerFilters {
  search?: string;
  page?:   number;
  limit?:  number;
}
